### PR TITLE
Get the SSL handshake failure being reported to messageHandler correctly

### LINKED ISSUE #504: MySQL TLS handshake failure could not be reported correctly
The CI does not pass in https://travis-ci.org/eclipse-vertx/vertx-sql-client/builds/636987648 and it is due to MySQL TLS tests failure.

This is because of regression in https://github.com/eclipse-vertx/vert.x/commit/3b685e70b3635a2ae5830efd52dbabe673a7cdcd.

MySQL handshake failure will trigger https://github.com/eclipse-vertx/vertx-sql-client/blob/d96e53f80c0066b377c43efbd1c6466bb0d06e51/vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/InitialHandshakeCommandCodec.java#L159

which then calls `chctx.fireChannelRead(resp);`, but the connection is closed thus the message could not be processed, so the message handler could not be called. Then the test hangs and fails for being timeout.

### PR DESCRIPTION
**Pull request by BillyYccc**
fix #504

### CODE REVIEW

File: vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/InitiateSslHandler.java [hunk 1]
```diff
@@ -41,7 +41,6 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception
 
   @Override
   public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
-    cause.printStackTrace();
```
Comment (aguibert) [inline vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/InitiateSslHandler.java]: this change will have a merge conflict with your other PR #505, I assume you can just undo this change?

File: vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLEncoder.java [hunk 2]
```diff
@@ -49,6 +49,14 @@ void write(CommandBase<?> cmd) {
     codec.completionHandler = resp -> {
       CommandCodec c = inflight.poll();
       resp.cmd = (CommandBase) c.cmd;
+      /*
+       * a bit hacky but we need this message delivered to the socket messageHandler
+       */
+      if (resp.cause() != null && resp.cause().getMessage().equals("SSL handshake failed")) {
```
Comment (aguibert) [inline vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLEncoder.java]: this does seem a bit hacky, where does the error message come from? Is there any chance it could change or be a localized (non-english) message?

File: vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/InitiateSslHandler.java (hunk 1 above)
Comment (BillyYccc) [reply vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/InitiateSslHandler.java]: no because this PR is for `3.8` branch.

File: vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLEncoder.java (hunk 2 above)
Comment (BillyYccc) [reply vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLEncoder.java]: The error is from https://github.com/eclipse-vertx/vertx-sql-client/blob/6d38d4b9f442642ecc6b6de425e23d012cd7270b/vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/InitiateSslHandler.java#L56

Because in Vert.x 3.8 the `NetSocket#upgradeToSsl` method does not have an async result to represent if it fails, so we let the failure propagated in the channel pipeline and gets the connection closed, then we can check the activity of channel to know if the SSL handshake is successful or not. We only need this trick in `3.8` branch which is different what I do in my another PR for `master` branch(i.e. 4.0 version).

**Comment by vietj** [comment]
@BillyYccc can we get a test for this, e.g using a wrong or expired certificate

**Comment by BillyYccc** [comment]
I have added a test which the client connects with a self-signed certificate to make the TLS handshake fail.

**Comment by BillyYccc** [comment]
can we merge this now?
