### PR TITLE
Evict broken Oracle pooled connection

### LINKED ISSUE #1173: Oracle Pool - pool stores closed connections and try to use them
Hi Thomas and all,
**short description about issue:** 
if Oracle connection closed by some reason (connectivity/firewall/etc), pool continue to keep closed connections and try to use for queries when connectivity restored instead of connection re-new. It's critical for usage of OraclePool.
Issue related only to Oracle (not reproduced in PgPool).

**Configuration:**
**quarkus.version:** 2.7.3.Final
**vertx-oracle-client:** 4.2.5.1
**smallrye-mutiny-vertx-oracle-client:** 2.18.1
**ojdbc11**: 21.4.0.0

Full info/logs/steps how to reproduce/logs and comparation with PgPool and Agoral Pool [located in github here](https://github.com/alexeysharandin/vertx-oracleclient-pool-bug)

All additional info available in [README.md](https://github.com/alexeysharandin/vertx-oracleclient-pool-bug#readme)

Please ping me if you have some questions or need additional clarifications.

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #1173

When the physical connection is broken (connection reset, firewall timeouts, ...etc), the Oracle connection methods throw `SQLExeception` on usage, but there is no way for Vert.x to be notified.

The fix consists in inspecting failures when a command is scheduled on the connection.
If the failure is fatal, then the underlying connection is closed.
This leads to eviction for pooled connection.

Commits can be reviewed individually.

### CODE REVIEW

File: vertx-pg-client/src/test/java/io/vertx/pgclient/PgClientTestBase.java [hunk 1]
```diff
@@ -1,37 +1,32 @@
 /*
- * Copyright (C) 2017 Julien Viet
+ * Copyright (c) 2011-2022 Contributors to the Eclipse Foundation
```
Comment (vietj) [inline vertx-pg-client/src/test/java/io/vertx/pgclient/PgClientTestBase.java:2]: can you avoid reformating and changing header that is not related to the PR ?

**Review by vietj — APPROVED** [review]
