### PR TITLE
Fix the incorrect hostname of proxy server in connection auto retry testsuite

### LINKED ISSUE #854: Connection refused in PgConnectionAutoRetryTest
### Version

Which version(s) did you encounter this bug? 4.0.0, 4.0.1-SNAPSHOT cc3b6c99c7110ad98fd350c3d7f51b997c907305

### Context

Trying to build vertx-pg-client fails in these tests:
PgConnectionAutoRetryTest.testConnRetrySuccess
PgConnectionAutoRetryTest.testConnSuccessWithoutRetry
PgConnectionAutoRetryTest.testPoolRetrySuccess
PgConnectionAutoRetryTest.testPoolSuccessWithoutRetry

```
testConnSuccessWithoutRetry(io.vertx.pgclient.tck.PgConnectionAutoRetryTest)  Time elapsed: 1.022 sec  <<< ERROR!
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.17.0.1:45965
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

The Exception is reported in
https://github.com/eclipse-vertx/vertx-sql-client/blob/4.0.0/vertx-pg-client/src/test/java/io/vertx/pgclient/tck/ClientConfig.java#L43
https://github.com/eclipse-vertx/vertx-sql-client/blob/4.0.0/vertx-pg-client/src/test/java/io/vertx/pgclient/tck/ClientConfig.java#L65

### Do you have a reproducer?

https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgConnectionAutoRetryTest.java

### Steps to reproduce

Build on Jenkins:
https://jenkins-aws.indexdata.com/job/folio-org/job/vertx-sql-client/job/master-vertx/
Complete log is available in the red box in the "Maven build" column.

### PR DESCRIPTION
**Pull request by julianladisch**
PgConnectionAutoRetryTest connects to the proxy using the
hostname returned by ContainerPgRule.
This differs from `localhost` in some CI environments, see #854 and
https://www.testcontainers.org/features/networking/#getting-the-container-host
This needs to be changed to `localhost`, the proxy hostname,
to make the tests succeed.

ConnectionAutoRetryTestBase connects to the database using
`localhost` as hostname. The hostname of the database differs
from `localhost` in some CI environments.
Use the hostname returned by ContainerPgRule to make the tests succeed.

Fixes #854

### CODE REVIEW

File: vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgConnectionAutoRetryTest.java [hunk 1]
```diff
@@ -42,6 +42,7 @@ public void tearDown(TestContext ctx) {
   protected void initialConnector(int proxyPort) {
     SqlConnectOptions proxyOptions = new PgConnectOptions(options);
     proxyOptions.setPort(proxyPort);
+    proxyOptions.setHost("localhost");
```
Comment (BillyYccc) [inline vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgConnectionAutoRetryTest.java:45]: can you update other auto retry tests(they all extends ConnectionAutoRetryTestBase) in this project as well?

**Review by BillyYccc — CHANGES_REQUESTED** [review]

File: vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgConnectionAutoRetryTest.java (hunk 1 above)
Comment (BillyYccc) [reply vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgConnectionAutoRetryTest.java:45]: The proxy server listening on a default host also seems not reliable for the testing, can we try to get rid of it and use the database host instead?

Comment (julianladisch) [reply vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgConnectionAutoRetryTest.java:45]: Each *ConnectionAutoRetryTest uses `proxyOptions.setHost("localhost")` now.

Comment (julianladisch) [reply vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgConnectionAutoRetryTest.java:45]: The proxy server uses `this.netServer.listen()`, this is listening on default host = "0.0.0.0" = all interfaces.
I don't see how this could be unreliable.
Vert.x always starts a NetServer on localhost. For starting a server running at some other address we need Docker to create that server on a docker network. This is a different feature and should be tested in a different test, not in the connection auto retry test.

**Review by BillyYccc — APPROVED** [review]

**Comment by BillyYccc** [comment]
Thanks for contributing!
